"""
Canonical journal taxonomy and matching hints used by CV extraction prompts.
"""

from __future__ import annotations

from typing import Iterable

JOURNALS = [
    "QUARTERLY JOURNAL OF ECONOMICS",
    "AMERICAN ECONOMIC REVIEW",
    "ECONOMETRICA",
    "REVIEW OF ECONOMIC STUDIES",
    "JOURNAL OF POLITICAL ECONOMY",
    "AMERICAN ECONOMIC JOURNAL-MACROECONOMICS",
    "AMERICAN ECONOMIC JOURNAL-APPLIED ECONOMICS",
    "JOURNAL OF THE EUROPEAN ECONOMIC ASSOCIATION",
    "AMERICAN ECONOMIC JOURNAL-ECONOMIC POLICY",
    "THEORETICAL ECONOMICS",
    "AMERICAN ECONOMIC JOURNAL-MICROECONOMICS",
    "QUANTITATIVE ECONOMICS",
    "REVIEW OF ECONOMICS AND STATISTICS",
    "ECONOMIC JOURNAL",
    "INTERNATIONAL ECONOMIC REVIEW",
    "JOURNAL OF ECONOMIC THEORY",
    "JOURNAL OF LABOR ECONOMICS",
    "JOURNAL OF MONETARY ECONOMICS",
    "RAND JOURNAL OF ECONOMICS",
    "JOURNAL OF INTERNATIONAL ECONOMICS",
    "JOURNAL OF PUBLIC ECONOMICS",
    "JOURNAL OF ECONOMETRICS",
    "JOURNAL OF DEVELOPMENT ECONOMICS",
]

JOURNAL_ABBREVIATION_RULE_LINES = (
    "AER = AMERICAN ECONOMIC REVIEW",
    "QJE = QUARTERLY JOURNAL OF ECONOMICS",
    "JPE = JOURNAL OF POLITICAL ECONOMY",
    "RES / RESTUD = REVIEW OF ECONOMIC STUDIES",
    "RESTAT = REVIEW OF ECONOMICS AND STATISTICS",
    "AEJ: Macro / Applied / Policy / Micro = corresponding AEJ variants",
    "IER = INTERNATIONAL ECONOMIC REVIEW",
    "JET = JOURNAL OF ECONOMIC THEORY",
    "JDE = JOURNAL OF DEVELOPMENT ECONOMICS",
    "JEEA = JOURNAL OF THE EUROPEAN ECONOMIC ASSOCIATION",
    "JME = JOURNAL OF MONETARY ECONOMICS",
    "JIE = JOURNAL OF INTERNATIONAL ECONOMICS",
    "JPubE = JOURNAL OF PUBLIC ECONOMICS",
    "JLE = JOURNAL OF LABOR ECONOMICS",
    "RAND = RAND JOURNAL OF ECONOMICS",
)


def _bullets(items: Iterable[str], *, prefix: str = "* ") -> str:
    return "\n".join(f"{prefix}{item}" for item in items)


def format_journal_bullets() -> str:
    return _bullets(JOURNALS, prefix="* ")


def format_journal_abbreviation_hints() -> str:
    return _bullets(JOURNAL_ABBREVIATION_RULE_LINES, prefix="  - ")
