"""
Clean local cache artifacts generated by the project.

Removes:
- all `__pycache__` directories under the repository
- all `.pyc` files under the repository
- `output/cache/` directory (staged extraction cache and other cached outputs)
"""

from __future__ import annotations

import shutil
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_CACHE_DIR = REPO_ROOT / "output" / "cache"


def remove_tree(path: Path) -> bool:
    if not path.exists():
        return False
    shutil.rmtree(path)
    return True


def remove_file(path: Path) -> bool:
    if not path.exists():
        return False
    path.unlink()
    return True


def main() -> None:
    removed_dirs: list[Path] = []
    removed_files: list[Path] = []

    for pycache_dir in REPO_ROOT.rglob("__pycache__"):
        if pycache_dir.is_dir() and remove_tree(pycache_dir):
            removed_dirs.append(pycache_dir)

    for pyc_file in REPO_ROOT.rglob("*.pyc"):
        if pyc_file.is_file() and remove_file(pyc_file):
            removed_files.append(pyc_file)

    if remove_tree(OUTPUT_CACHE_DIR):
        removed_dirs.append(OUTPUT_CACHE_DIR)

    print(f"Removed {len(removed_dirs)} directories and {len(removed_files)} files.")
    if removed_dirs:
        print("Directories:")
        for path in sorted(removed_dirs):
            print(f"- {path.relative_to(REPO_ROOT)}")
    if removed_files:
        print("Files:")
        for path in sorted(removed_files):
            print(f"- {path.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
